apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  PORT: "8080"
  DB_HOST: "postgres-service"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "example_db"
  DB_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: evinaram/backend-express-psql:latest
        envFrom:
          - configMapRef:
              name: backend-configmap
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
